export const GET_USER_LIST = "GET_USER_LIST";
export const SET_USER_ADMIN_LIST = "SET_USER_ADMIN_LIST";
export const GET_USER_INFOR = "GET_USER_INFOR";
export const SET_USER_DETAILS_INFOR = "SET_USER_DETAILS_INFOR";
export const SET_USER_DETAILS_TICKET_INFOR = "SET_USER_DETAILS_TICKET_INFOR";
export const LOGIN = "LOGIN";
